version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn claudiu_first_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - aso_db
  aso_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx/chat.com.crt:/etc/nginx/chat.com.crt
      - ./nginx/chat.com.key:/etc/nginx/chat.com.key  
    ports:
      - 1337:82
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
