# Generated by Django 4.0 on 2022-12-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
