# Generated by Django 4.0 on 2022-12-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_chat', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hotel_Main_Img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
