# Generated by Django 4.0 on 2022-12-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso_chat', '0005_message_hotel_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='hotel_Main_Img',
            new_name='image',
        ),
    ]
