# Generated by Django 4.0 on 2022-12-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_chat', '0008_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomregistration',
            name='status',
            field=models.CharField(blank='False', max_length=10),
        ),
    ]
