# Generated by Django 4.0 on 2022-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso_chat', '0009_alter_roomregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
